### ISSUE TITLE
.NET 7 NuGet package?

### ISSUE THREAD

**Issue by NickStrupat** [c-ohle/RationalNumerics#9]
How are things going on your end? Love the trajectory of this package and I hope it gets into .NET in the future!

**Comment by c-ohle** [comment]
Hi, thanks, the .NET 7 NuGet version is coming soon.
I need to finish another job at first but the current GitHub code version can already compiled for .NET 7 to get a .NET 7 assembly. 
The new INumber-based interfaces have already been fully implemented, but not all have been finally optimized and tested.
The documentation is not up to date and some experimental code needs to be consolidated.
That's why there is no new NuGet version yet.

**Comment by NickStrupat** [comment]
Thanks! I'll use a git submodule for now.
